.TH LEXLEO 1 "April 2026" "LexLeo 0.1.0" "User Commands"

.SH NAME
lexleo \- LexLeo command-line application

.SH SYNOPSIS
.B lexleo

.SH DESCRIPTION
Runs the LexLeo language CLI.

.SH FILES
.TP
/usr/bin/lexleo
Executable command installed in the user PATH.

.TP
/etc/lexleo/lexleo.conf
System configuration file.

.TP
/usr/share/doc/lexleo/README.txt
Additional documentation.

.TP
$HOME/.local/state/lexleo/lexleo.log
Default log file path used when no valid log_path is provided in the system
configuration file.

.SH AUTHOR
Sylvain Labopin

.SH LICENSE
GPL-3.0-or-later
