.TH LEXLEO 1 "April 2026" "LexLeo 0.1.0" "User Commands"

.SH NAME
lexleo \- LexLeo command-line application

.SH SYNOPSIS
.B lexleo

.SH DESCRIPTION
Runs the LexLeo language command-line application.

.SH FILES
.TP
/usr/local/bin/lexleo
Executable command installed in the user PATH.

.TP
/usr/local/etc/lexleo/lexleo.conf
System configuration file.

.TP
/usr/local/share/doc/lexleo/README.txt
Additional documentation.

.TP
/usr/local/share/doc/lexleo/LICENSE.txt
License file.

.TP
/usr/local/share/man/man1/lexleo.1
Manual page.

.TP
$HOME/Library/Logs/LexLeo/lexleo.log
Suggested default log file path on macOS when no valid log_path is provided in
the system configuration file.

.SH AUTHOR
Sylvain Labopin

.SH LICENSE
GPL-3.0-or-later
